---
title: "STAT 311 Reference Sheet Chapter 4"
output: html_document
---

<style>

    
        /* Header colors for sections */
        h3 {
            color: orange;
            text-align: center;
            background-color: #4B2D83;
            padding: 10px;
            border-radius: 3px;
            display: inline-block;
        }
        
        h4 {
            color: #000000;
            text-align: center;

            background-color: #a6c8ff;
            padding: 1px;
            border-radius: 3px;
            width: 200px;
        }
        
        /* table rows for each function*/
        tr {
            display: flex;
            flex-direction: column
        }
        
        /* Styling for the specific table */
    .example-table th {
        background-color: #4B2D83;
        color: white;
        padding: 10px;
    }

    .example-table td {
        padding: 8px;
        border: 1px solid #ddd;
    }
    
    .example-table tr {
        display: table-row; /* Override general display: flex */
    }

    .example-table tr:nth-child(even) {
        background-color: #f9f9f9;
    }
}

</style>

<div>
  <table>
    <tr>
    <td> <h3>Transforming Variables</h3> </td>
    <td> <h4> Syntax </h4> </td>
    <td> <p> ```<dataset> <- <dataset> %>%```
    <br>&emsp;&emsp;
     ```mutate(<new_var1> = {operation}(<var1>),``` <br>&emsp;&emsp;
     ```<new_var2> = ...)```
     </p> </td>
    <td> <h4> Usage </h4> </td> 
    <td> <p> We often try to make simple transformation of one or both variables (explanatory and/or response) when the distribution is heavily skewed in order to achieve a linear model in the transformed scale. A common transformation is the common logarithm ```log10```. <b>Keep in mind what transformations you did when interpreting a model.</b></p> </td>
    </tr>
    <tr>
      <td> <h3> Linear Model using R (lm function) </h3> </td>
      <td> <h4> Syntax </h4> </td>
      <td> <p> ```<model_name> <- lm(<response_variable> ~ <explanatory_variable>, data = <dataset>)``` </p> </td>
      <td> <h4> Usage </h4> </td> 
      <td> <p> Generates a linear model for the relationship between two <b>quantitative</b> variables. </p> </td>
    </tr>
    <tr>
      <td> <h3> Main Effects Model using R </h3> </td>
      <td> <h4> Syntax </h4> </td>
      <td> <p> ```<model_name> <- lm(<response_variable> ~ <explanatory_variable> + <other_predictor> + ... + <last_predictor>, data = <dataset>)``` </p> </td>
      <td> <h4> Usage </h4> </td> 
      <td> <p> Generates two equations using the main effects linear model for the relationship between <b>a categorical and quantitative predictor</b> and a <b>quantitative response variable</b>. The y-intercept varies between the two equations, but slope doesn't. </p> </td>
    </tr>
    <tr>
      <td> <h3> Interaction Effects Model using R </h3> </td>
      <td> <h4> Syntax </h4> </td>
      <td> <p> ```<model_name> <- lm(<response_variable> ~ <explanatory_variable> * <other_predictor>, data = <dataset>)``` </p> </td>
      <td> <h4> Usage </h4> </td> 
      <td> <p> Generates two equations using the interaction effects linear model for the relationship between <b>a categorical and quantitative predictor</b> and a <b>quantitative response variable</b>. The y-intercept and slope varies between the two equations. </p> </td>
    </tr>
    <tr>
      <td> <h3> Tidy View of Linear Model </h3> </td>
      <td> <h4> Syntax </h4> </td>
      <td> <p> ```<model_name> %>% tidy()``` </p> </td>
      <td> <h4> Usage </h4> </td> 
      <td> <p> This step comes after generating a model with the ```lm``` function. It can be used to write the equation of the model using the <b>estimate column</b>.</p> </td>    
      <td> <h4> Solving for a Basic Linear Model Equation </h4> </td> 
      <td> <p> \<response_variable>_hat = (Intercept) + (estimate_value_of_explanatory_variable) * \<explanatory_variable_observation> </p> </td>
      <td> <p> <u>For example (explanatory = car_age/response = horsepower):</u><br>
  <table class="example-table">
    <tr>
      <th>#</th>
      <th>term \<chr></th>
      <th>estimate \<dbl></th>
    </tr>
    <tr><td>1</td><td>(Intercept)</td><td>100</td></tr>
    <tr><td>2</td><td>car_age</td><td>-2</td></tr>
    </table>
  
  horsepower_hat = 100 + (-2 * car_age)
      <br><br>
      Where horsepower_hat is a predicted value and car_age is the age of the car that is being observed (so that we can predict its horsepower using the model).<b> All of the estimate values are just examples.</b>
      </p> </td>
      <td> <h4> Solving for Main Effects Linear Model Equations (with a categorical predictor)</h4> </td> 
      <td> <p> \<response_variable>_hat = (Intercept) + (estimate_value_of_categorical_predictor) * \<categorical_predictor>yes + (estimate_value_of_explanatory_variable) * \<explanatory_variable_observation> </p> </td>
      <td> <p> <u>For example (explanatory = car_age/response = horsepower/categorical predictor = sedan OR suv):</u><br></p>
      
  <table class="example-table">
    <tr>
      <th>#</th>
      <th>term \<chr></th>
      <th>estimate \<dbl></th>
    </tr>
    <tr><td>1</td><td>(Intercept)</td><td>90</td></tr>
    <tr><td>2</td><td>car_age</td><td>-1.5</td></tr>
    <tr><td>3</td><td>sedanyes</td><td>20</td></tr>
  </table>
      
  <p>horsepower_hat = 90 + (20 * sedanyes) + (-1.5 * car_age)
      <br><br>
      <u>If the car is a sedan (sedanyes = 1):</u><br>
      horsepower_hat = 110 - 1.5 * car_age<br><br>
      <u>If the car is an suv (sedanyes = 0):</u><br>
      horsepower_hat = 90 - 1.5 * car_age<br><br>
      Where horsepower_hat is a predicted value and car_age is the age of the car that is being observed (so that we can predict its horsepower using the model). sedanyes is a binary used to keep track of whether the car is a sedan or not.<b> All of the estimate values are just examples.</b><br><br>
      
  <u>Two Quantitative Predictors</u><br>
  If we have another quantitative predictor, other than the explanatory variable, then we would just have the estimate of that value be multiple by the observed value (just like the numerical explanatory variable). This would output the equation of a plane rather than a line.<br><br>
      
  \<response_variable>_hat = (Intercept) + (estimate_value_of_numerical_predictor) * \<numerical_predictor_observation> + (estimate_value_of_explanatory_variable) * \<explanatory_variable_observation>


  </p> </td>
      
  <td> <h4> Solving for Interaction Effects Linear Model Equations (with a categorical predictor)</h4> </td> 
      <td> <p> \<response_variable>_hat = (Intercept) + (estimate_value_of_categorical_predictor) * \<categorical_predictor>yes + (estimate_value_of_explanatory_variable) * \<explanatory_variable_observation> </p> </td>
      <td> <p> <u>For example (explanatory = car_age/response = horsepower/categorical predictor = sedan OR suv):</u><br></p>
      
  
  
  <table class="example-table">
    <tr>
      <th>#</th>
      <th>term \<chr></th>
      <th>estimate \<dbl></th>
    </tr>
    <tr><td>1</td><td>(Intercept)</td><td>85</td></tr>
    <tr><td>2</td><td>car_age</td><td>-1.7</td></tr>
    <tr><td>3</td><td>sedanyes</td><td>17</td></tr>
    <tr><td>4</td><td>car_age:sedanyes</td><td>0.12</td></tr>
  </table>
      
  <p>horsepower_hat = 85 + (17 * sedanyes) + (-1.7 * car_age) + (0.12 * car_age * sedanyes)
      <br><br>
      <u>If the car is a sedan (sedanyes = 1):</u><br>
      horsepower_hat = 102 - 1.58 * car_age<br><br>
      <u>If the car is an suv (sedanyes = 0):</u><br>
      horsepower_hat = 85 - 1.5 * car_age<br><br>
      Where horsepower_hat is a predicted value and car_age is the age of the car that is being observed (so that we can predict its horsepower using the model). sedanyes is a binary used to keep track of whether the car is a sedan or not. <b>All of the estimate values are just examples.</b>
      </p> </td>
      
      
  </tr>
      <tr>
      <td> <h3> Scatterplot Matrix </h3> </td>
      <td> <h4> Syntax </h4> </td>
      <td> <p> ```library(GGally)``` <br></p> </td>
      <td> <p> ```<dataframe> %>%``` </p> </td>
      <td> <p> &emsp;```select(<variable_1>, <variable_2>, <variable_3>, ...) %>%``` </p> </td>
      <td> <p> &emsp; &emsp;```ggpairs(title="What you are going to call the scatterplot matrix")``` </p> </td>
      <td> <h4> Usage </h4> </td> 
      <td> <p> Generates a scatterplot matrix between the specified variables, which contains scatterplots, graphs, and correlations coefficients. This tool is helpful in determining how highly correlated multiple variables in a dataset are. </p> </td>
    </tr>
      <tr>
      <td> <h3> Goodness of Fit Measures </h3> </td>
      <td> <h4> Syntax </h4> </td>
      <td> <p> ```glance(<model_name>)``` Gets all the goodness of fit measures </p> </td>
      <td> <p> ```glance(<model_name>) %>% select(r.squared)``` Gets the R squared value of the model to the data </p> </td>
      <td> <p> ```glance(<model_name>) %>% select(adj.r.squared)``` Gets the adjusted R squared value of the model to the data </p> </td>
      <td> <h4> Usage </h4> </td> 
      <td> <p> Provides the goodness of fit measure that are typically used (how well model fits observations). </p> </td>
    </tr>
    
  </table>
  
</div>