---
title: "STAT 311 Cheatsheet"
output: html_document
---


<style>
    /* Center the entire Table of Contents */
    #toc {
        width: 60%;
        margin: 0 auto;
        font-family: Arial, sans-serif;
        font-size: 1.1em;
        color: #333;
    }

    /* Header Styling */
    #toc h2 {
        text-align: center;
        color: #4B2D83;
        font-size: 1.8em;
        margin-bottom: 20px;
        border-bottom: 2px solid #4B2D83;
        padding-bottom: 10px;
    }

    /* List Item Styling */
    #toc ul {
        list-style: none;
        padding: 0;
    }

    #toc li {
        margin: 15px 0;
        padding: 10px;
        background-color: #f7f7f7;
        border-radius: 5px;
        text-align: center;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    #toc a {
        text-decoration: none;
        color: #4B2D83;
        font-weight: bold;
        transition: color 0.3s;
    }

    #toc a:hover {
        color: #FF8C00;
    }

    /* Author Subheading Styling */
    .authors {
        text-align: left;
        font-family: 'Arial', sans-serif;
        font-size: 1em; /* Slightly smaller font size */
        font-weight: bold;
        margin-bottom: 20px;
    }
</style>

<div class="authors">
  Authors: Krish Doshi and Dylan Nguyen
</div>

<div id="toc">
  <h2>Table of Contents</h2>
  <ul>
    <li>
      <a href="Chapters/RStudioHelp.html">RStudio Help</a>
    </li>
    <li>
      <a href="Chapters/RmdIntroduction.html">R/Rmd Introduction: Hello R</a>
    </li>
    <li>
      <a href="Chapters/RmdShortcuts.html">Keyboard Shortcuts</a>
    </li>
    <li>
      <a href="Chapters/Chapter1.html">Chapter 1: Data wrangling</a>
    </li>
    <li>
      <a href="Chapters/Chapter2.html">Chapter 2: Data wrangling</a>
    </li>
    <li>
      <a href="Chapters/Chapter3.html">Chapter 3: Visualizing data (ggplot)</a>
    </li>
    <li>
      <a href="Chapters/Chapter4.html">Chapter 4: Fitting linear models (tidymodels)</a>
    </li>
    <li>
      <a href="Chapters/Chapter5.html">Chapter 5: Bootstrapping</a>
    </li>
  </ul>
</div>
